AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patient_directory

  Sample SAM Template for patient_directory

Globals:
  Function:
    Timeout: 20

Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: com.lambda.aws.function.PatientCheckout::handler
      Runtime: java11
      MemorySize: 512
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutDLQ
      Policies:
        - S3ReadPolicy:
          BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
          TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  BillManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: com.lambda.aws.function.BillManagement::handler
      Runtime: java11
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
    ErrorHandlingFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: patientcheckout
        Handler: com.lambda.aws.errorhandler.ErrorHandler::handler
        Runtime: java11
        MemorySize: 512
        Events:
          SNSEvent:
            Type: SNS
            Properties:
              Topic: !Ref PatientCheckoutDLQ

