AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello_lambda

  Sample SAM Template for hello_lambda

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: com.lambda.aws.DataTypes::coldstartBasics
      Runtime: java11
      MemorySize: 512
      Timeout: 6
      Environment:
        Variables:
          restapiurl: rest-api